export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'


export const POSITIONS_REQUEST = 'POSITIONS_REQUEST'
export const POSITIONS_SUCCESS = 'POSITIONS_SUCCESS'
export const POSITIONS_FAIL = 'POSITIONS_FAIL'
