export const MOBILE_SCREEN_SIZE = "MOBILE_SCREEN_SIZE";
export const TABLET_SCREEN_SIZE = "TABLET_SCREEN_SIZE";
export const LAPTOP_SCREEN_SIZE = "LAPTOP_SCREEN_SIZE";
export const DESKTOP_SCREEN_SIZE = "DESKTOP_SCREEN_SIZE";



